"""Domain entities for the warehouse AMR simulation."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .config import EdgeNodeClassConfig, OperationModeConfig, TaskClassConfig


TASK_STATUSES = (
    "generated",
    "queued",
    "running",
    "completed",
    "dropped",
    "violated",
)

TASK_CLASSES = (
    "obstacle_detection",
    "perception",
    "localization_slam",
    "path_replanning",
    "inventory_recognition",
    "telemetry_diagnostics",
)


@dataclass
class Task:
    """A computation task generated by a warehouse robot."""

    id: str
    robot_id: str
    task_class: str
    arrival_time: float
    input_size_mbit: float
    output_size_mbit: float
    cpu_required: float
    memory_required: float
    gpu_required: float
    deadline_ms: float
    priority: int
    hard_deadline: bool
    assigned_node_id: str | None = None
    start_time: float | None = None
    finish_time: float | None = None
    status: str = "generated"
    utility: float = 0.0
    cost: float = 0.0
    welfare_contribution: float = 0.0
    robot_payment: float = 0.0
    node_compensation: float = 0.0
    externality_estimate: float = 0.0
    metadata: dict[str, Any] = field(default_factory=dict)

    def total_data_mbit(self) -> float:
        """Total data transferred for this task."""

        return self.input_size_mbit + self.output_size_mbit


@dataclass
class AccessPoint:
    """Warehouse wireless access point."""

    id: str
    position: tuple[float, float]
    coverage_radius_m: float


@dataclass
class NodeReservation:
    """Scheduled execution reservation on an edge node."""

    task_id: str
    start_time: float
    finish_time: float
    cpu_required: float
    memory_required: float
    gpu_required: float


@dataclass
class Robot:
    """Autonomous mobile robot operating in the warehouse."""

    id: str
    position: tuple[float, float]
    velocity: tuple[float, float]
    max_speed_mps: float
    working_speed_mps: float
    payload_kg: float
    mission_importance: float
    task_generator: Any
    local_network_state_summary: dict[str, float] = field(default_factory=dict)
    video_input_rate_mbps: float = 0.0


@dataclass
class EdgeNode:
    """Edge compute node serving nearby robots."""

    id: str
    node_class: str
    cpu_capacity_norm: float
    memory_capacity_norm: float
    gpu_capacity_norm: float
    current_cpu_load: float = 0.0
    current_memory_load: float = 0.0
    current_gpu_load: float = 0.0
    queue: list[str] = field(default_factory=list)
    running_tasks: list[str] = field(default_factory=list)
    failure_flag: bool = False
    failure_schedule: list[tuple[int, int]] = field(default_factory=list)
    current_operation_mode: str = "normal"
    previous_operation_mode: str = "normal"
    last_observation: list[float] = field(default_factory=list)
    last_auction_stats: dict[str, float] = field(default_factory=dict)
    reservations: list[NodeReservation] = field(default_factory=list)
    position: tuple[float, float] = (0.0, 0.0)
    attached_access_point_id: str | None = None

    @classmethod
    def from_class_config(
        cls,
        node_id: str,
        node_class: EdgeNodeClassConfig,
        position: tuple[float, float],
        attached_access_point_id: str | None,
        operation_mode: str,
    ) -> "EdgeNode":
        """Create an edge node from a class configuration."""

        return cls(
            id=node_id,
            node_class=node_class.name,
            cpu_capacity_norm=node_class.cpu_capacity_norm,
            memory_capacity_norm=node_class.memory_capacity_norm,
            gpu_capacity_norm=node_class.gpu_capacity_norm,
            current_operation_mode=operation_mode,
            previous_operation_mode=operation_mode,
            position=position,
            attached_access_point_id=attached_access_point_id,
        )

    def exposed_capacity(self, operation_modes: dict[str, OperationModeConfig]) -> dict[str, float]:
        """Compute currently exposed capacity from the active operation mode."""

        mode = operation_modes[self.current_operation_mode]
        if self.failure_flag:
            return {"cpu": 0.0, "memory": 0.0, "gpu": 0.0}
        return {
            "cpu": self.cpu_capacity_norm * mode.cpu_exposure,
            "memory": self.memory_capacity_norm * mode.memory_exposure,
            "gpu": self.gpu_capacity_norm * mode.gpu_exposure,
        }

    def utilization(self, operation_modes: dict[str, OperationModeConfig]) -> dict[str, float]:
        """Return current resource utilization under the exposed capacity."""

        exposed = self.exposed_capacity(operation_modes)
        return {
            "cpu": 0.0 if exposed["cpu"] <= 0.0 else self.current_cpu_load / exposed["cpu"],
            "memory": 0.0 if exposed["memory"] <= 0.0 else self.current_memory_load / exposed["memory"],
            "gpu": 0.0 if exposed["gpu"] <= 0.0 else self.current_gpu_load / exposed["gpu"],
        }

    def update_loads(self, tasks_by_id: dict[str, Task], now_ms: float) -> None:
        """Refresh queue, running tasks and current loads from reservations."""

        running: list[str] = []
        queued: list[str] = []
        cpu_load = 0.0
        memory_load = 0.0
        gpu_load = 0.0
        for reservation in self.reservations:
            task = tasks_by_id[reservation.task_id]
            if reservation.finish_time <= now_ms:
                continue
            if reservation.start_time <= now_ms:
                running.append(task.id)
                cpu_load += reservation.cpu_required
                memory_load += reservation.memory_required
                gpu_load += reservation.gpu_required
                if task.status in {"generated", "queued"}:
                    task.status = "running"
                    task.start_time = reservation.start_time
                    task.assigned_node_id = self.id
            else:
                queued.append(task.id)
                if task.status == "generated":
                    task.status = "queued"
                    task.assigned_node_id = self.id
        self.running_tasks = sorted(running)
        self.queue = sorted(queued)
        self.current_cpu_load = cpu_load
        self.current_memory_load = memory_load
        self.current_gpu_load = gpu_load

    def cleanup_finished(self, tasks_by_id: dict[str, Task], now_ms: float) -> list[Task]:
        """Finalize tasks completed up to the provided timestamp."""

        finished: list[Task] = []
        remaining: list[NodeReservation] = []
        for reservation in self.reservations:
            task = tasks_by_id[reservation.task_id]
            if reservation.finish_time <= now_ms:
                task.finish_time = reservation.finish_time
                finished.append(task)
            else:
                remaining.append(reservation)
        self.reservations = remaining
        self.update_loads(tasks_by_id, now_ms)
        return finished

    def clear_all_work(self, tasks_by_id: dict[str, Task], now_ms: float) -> list[Task]:
        """Drop all tasks scheduled on this node, used for failure events."""

        dropped: list[Task] = []
        for reservation in self.reservations:
            task = tasks_by_id[reservation.task_id]
            if task.status not in {"completed", "violated", "dropped"}:
                task.status = "dropped"
                task.finish_time = now_ms
                dropped.append(task)
        self.reservations.clear()
        self.update_loads(tasks_by_id, now_ms)
        return dropped

    def local_observation_builder(
        self,
        operation_modes: dict[str, OperationModeConfig],
        queue_class_distribution: dict[str, float],
        local_network_summary: dict[str, float],
    ) -> list[float]:
        """Build a local observation vector for QMIX."""

        exposed = self.exposed_capacity(operation_modes)
        mode_names = list(operation_modes)
        current_mode_index = float(mode_names.index(self.current_operation_mode))
        previous_mode_index = float(mode_names.index(self.previous_operation_mode))
        util = self.utilization(operation_modes)
        observation = [
            0.0 if self.cpu_capacity_norm == 0 else max(exposed["cpu"] - self.current_cpu_load, 0.0) / self.cpu_capacity_norm,
            0.0 if self.memory_capacity_norm == 0 else max(exposed["memory"] - self.current_memory_load, 0.0) / self.memory_capacity_norm,
            0.0 if self.gpu_capacity_norm == 0 else max(exposed["gpu"] - self.current_gpu_load, 0.0) / self.gpu_capacity_norm,
            float(len(self.queue)),
            util["cpu"],
            util["memory"],
            util["gpu"],
            1.0 if self.failure_flag else 0.0,
            current_mode_index,
            previous_mode_index,
            local_network_summary.get("avg_latency_ms", 0.0),
            local_network_summary.get("avg_bandwidth_mbps", 0.0),
            local_network_summary.get("degraded_link_fraction", 0.0),
            self.last_auction_stats.get("allocated_task_count", 0.0),
            self.last_auction_stats.get("average_welfare_contribution", 0.0),
            self.last_auction_stats.get("average_payment", 0.0),
            self.last_auction_stats.get("exposed_capacity_utilization", 0.0),
            self.last_auction_stats.get("scarcity_metric", 0.0),
        ]
        for task_class in TASK_CLASSES:
            observation.append(queue_class_distribution.get(task_class, 0.0))
        self.last_observation = observation
        return observation


def default_queue_distribution(tasks: list[Task]) -> dict[str, float]:
    """Compute a normalized class distribution for a task list."""

    if not tasks:
        return {task_class: 0.0 for task_class in TASK_CLASSES}
    total = float(len(tasks))
    return {
        task_class: sum(1.0 for task in tasks if task.task_class == task_class) / total
        for task_class in TASK_CLASSES
    }


def operation_mode_exposure(
    node: EdgeNode,
    operation_modes: dict[str, OperationModeConfig],
) -> tuple[float, float, float]:
    """Return the exposed capacities as a tuple."""

    capacity = node.exposed_capacity(operation_modes)
    return (capacity["cpu"], capacity["memory"], capacity["gpu"])
